### PR TITLE
delete deployments and statefulsets first before deleting namespace

### PR DESCRIPTION
**Pull request by lahabana**

### CODE REVIEW

**Comment by lahabana** [comment]
We're still seeying `AfterAll` failures: https://github.com/Kong/mesh-perf/actions/runs/6166260277/job/16735463601

My guess is that we could be a bit nicer by deleting the parent resource first

**Comment by michaelbeaumont** [comment]
Hmm why does it return

```
error while running command: exit status 1; Error from server: etcdserver: leader changed
```

**Comment by lahabana** [comment]
I guess etcd is overwhelmed that we delete 2k pods at once

**Comment by lahabana** [comment]
It passed lately so maybe it's fine...

**Pull request closed without merging**
